version: '3.9'
services:
  mongodb:
    image: mongo:7.0-rc-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
      

  golang-app:
    container_name: golang-app
    image: catfact/golang-app:1.0.4
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.2
    networks:
      - app-network

networks:
  app-network:
